# yaml-language-server: $schema=https://coderabbit.ai/integrations/schema.v2.json
reviews:
  profile: assertive
  high_level_summary_instructions: Keep the summary short and concise
  review_status: false
  commit_status: false
  changed_files_summary: false
  estimate_code_review_effort: false
  suggested_reviewers: false
  in_progress_fortune: false
  poem: false
