/**
 * Copyright (c) Siemens 2016 - 2025
 * SPDX-License-Identifier: MIT
 */
export const DASHBOARDS_NG_MAPPINGS: { [symbol: string]: string } = {
  'CONFIG_TOKEN': '@siemens/dashboards-ng',
  'Config': '@siemens/dashboards-ng',
  'createWidgetConfig': '@siemens/dashboards-ng',
  'DashboardToolbarItem': '@siemens/dashboards-ng',
  'DashboardToolbarItemAction': '@siemens/dashboards-ng',
  'DashboardToolbarItemLink': '@siemens/dashboards-ng',
  'DashboardToolbarItemRouterLink': '@siemens/dashboards-ng',
  'DEFAULT_GRIDSTACK_OPTIONS': '@siemens/dashboards-ng',
  'DEFAULT_WIDGET_STORAGE_TOKEN': '@siemens/dashboards-ng',
  'FederatedModule': '@siemens/dashboards-ng',
  'GridConfig': '@siemens/dashboards-ng',
  'LoadRemoteModuleEsmOptions': '@siemens/dashboards-ng',
  'LoadRemoteModuleManifestOptions': '@siemens/dashboards-ng',
  'LoadRemoteModuleOptions': '@siemens/dashboards-ng',
  'LoadRemoteModuleScriptOptions': '@siemens/dashboards-ng',
  'NEW_WIDGET_PREFIX': '@siemens/dashboards-ng',
  'ObjectFit': '@siemens/dashboards-ng',
  'provideSiDashboardsTranslatableOverrides': '@siemens/dashboards-ng/translate',
  'registerModuleFederatedWidgetLoader': '@siemens/dashboards-ng/module-federation',
  'SetupComponentFn': '@siemens/dashboards-ng',
  'setupWidgetEditor': '@siemens/dashboards-ng',
  'setupWidgetInstance': '@siemens/dashboards-ng',
  'SI_DASHBOARD_CONFIGURATION': '@siemens/dashboards-ng',
  'SI_WIDGET_STORE': '@siemens/dashboards-ng',
  'SiD': '@siemens/dashboards-ng',
  'SiDashboardsNgModule': '@siemens/dashboards-ng',
  'SiDefaultWidgetStorage': '@siemens/dashboards-ng',
  'SiFlexibleDashboardComponent': '@siemens/dashboards-ng',
  'SiGridComponent': '@siemens/dashboards-ng',
  'SiWidgetCatalogComponent': '@siemens/dashboards-ng',
  'SiWidgetInstanceEditorDialogComponent': '@siemens/dashboards-ng',
  'STORAGE_KEY': '@siemens/dashboards-ng',
  'WebComponent': '@siemens/dashboards-ng',
  'Widget': '@siemens/dashboards-ng',
  'WidgetComponentFactory': '@siemens/dashboards-ng',
  'WidgetComponentTypeFactory': '@siemens/dashboards-ng',
  'WidgetConfig': '@siemens/dashboards-ng',
  'WidgetConfigEvent': '@siemens/dashboards-ng',
  'WidgetConfigStatus': '@siemens/dashboards-ng',
  'widgetFactoryRegistry': '@siemens/dashboards-ng',
  'WidgetImage': '@siemens/dashboards-ng',
  'WidgetInstance': '@siemens/dashboards-ng',
  'WidgetInstanceEditor': '@siemens/dashboards-ng',
  'WidgetInstanceEditorWizard': '@siemens/dashboards-ng',
  'WidgetInstanceEditorWizardState': '@siemens/dashboards-ng',
  'WidgetPositionConfig': '@siemens/dashboards-ng',
  'SimplDashboardsNgModule': '@siemens/dashboards-ng'
};
