/**
 * Copyright (c) Siemens 2016 - 2025
 * SPDX-License-Identifier: MIT
 */
export const MAPS_NG_MAPPINGS: { [symbol: string]: string } = {
  'ANIMATION_DURATION': '@siemens/maps-ng',
  'CLUSTER_CHARTS_FRAGMENTS': '@siemens/maps-ng',
  'CLUSTER_RADIUS_SIZE': '@siemens/maps-ng',
  'ColorPalette': '@siemens/maps-ng',
  'ColorPalettes': '@siemens/maps-ng',
  'DEFAULT_CLUSTER_CLICK_ZOOM': '@siemens/maps-ng',
  'DEFAULT_CLUSTER_DISTANCE': '@siemens/maps-ng',
  'DEFAULT_CLUSTER_TYPE': '@siemens/maps-ng',
  'DEFAULT_DONUT_RATIO': '@siemens/maps-ng',
  'DEFAULT_FEATURE_CLICK_ZOOM': '@siemens/maps-ng',
  'DEFAULT_FEATURE_SELECT_ZOOM': '@siemens/maps-ng',
  'DEFAULT_FIT_PADDING': '@siemens/maps-ng',
  'DEFAULT_GLOBAL_ZOOM': '@siemens/maps-ng',
  'DEFAULT_ICON_SCALE': '@siemens/maps-ng',
  'DEFAULT_ICON': '@siemens/maps-ng',
  'DEFAULT_OFFSET': '@siemens/maps-ng',
  'DEFAULT_STROKE_WEIGHT': '@siemens/maps-ng',
  'GEOJSON_LAYER': '@siemens/maps-ng',
  'Grouping': '@siemens/maps-ng',
  'IconMarkerOptions': '@siemens/maps-ng',
  'LabelOptions': '@siemens/maps-ng',
  'LAYER_NAME': '@siemens/maps-ng',
  'MapPoint': '@siemens/maps-ng',
  'MapPointMetaData': '@siemens/maps-ng',
  'MapService': '@siemens/maps-ng',
  'MarkerOptions': '@siemens/maps-ng',
  'MarkerStatusType': '@siemens/maps-ng',
  'MAX_CLUSTER_BUILDINGS': '@siemens/maps-ng',
  'OverlayNativeProperties': '@siemens/maps-ng',
  'POINTS_LAYER': '@siemens/maps-ng',
  'provideSiMapsTranslatableOverrides': '@siemens/maps-ng/translate',
  'RenderOptions': '@siemens/maps-ng',
  'SIEMENS_FONT_LABELS': '@siemens/maps-ng',
  'SIEMENS_FONT': '@siemens/maps-ng',
  'SiMapComponent': '@siemens/maps-ng',
  'SiMapModule': '@siemens/maps-ng',
  'SiMapPopoverComponent': '@siemens/maps-ng',
  'SiMapsNgModule': '@siemens/maps-ng',
  'SiMapTooltipComponent': '@siemens/maps-ng',
  'TOOLTIP_FEATURES_TO_DISPLAY': '@siemens/maps-ng',
  'SimplMapsNgModule': '@siemens/maps-ng'
};
