name: Publish Documentation
on:
  push:
    branches:
      - main

permissions: read-all

jobs:
  build-and-test:
    uses: ./.github/workflows/build-and-test.yaml
    permissions:
      contents: read
      pull-requests: write
      id-token: write
    secrets:
      SIEMENS_NPM_TOKEN: ${{ secrets.SIEMENS_NPM_TOKEN }}
      SIEMENS_NPM_USER: ${{ secrets.SIEMENS_NPM_USER }}
      MAPTILER_KEY: ${{ secrets.MAPTILER_KEY }}

  publish-documentation:
    environment: github-pages
    runs-on: ubuntu-24.04
    permissions:
      pages: write
      id-token: write
    needs:
      - build-and-test
    steps:
      - uses: actions/configure-pages@45bfe0192ca1faeb007ade9deae92b16b8254a0d # v6
      - uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8
        with:
          name: pages
          path: dist/design
      - uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8
        with:
          name: coverage-reports
          path: coverage-reports
      - run: |
          cp coverage-reports/coverage-summary.json dist/design/coverage-summary.json
          cp -r coverage-reports dist/design/coverage
      - uses: actions/upload-pages-artifact@7b1f4a764d45c48632c6b24a0339c27f5614fb0b # v4
        with:
          path: 'dist/design'
      - uses: actions/deploy-pages@cd2ce8fcbc39b97be8ca5fce6e763baed58fa128 # v5
