name: Publish Documentation
on:
  push:
    branches:
      - main

jobs:
  build-and-test:
    uses: ./.github/workflows/build-and-test.yaml
    secrets:
      SIEMENS_NPM_TOKEN: ${{ secrets.SIEMENS_NPM_TOKEN }}
      SIEMENS_NPM_USER: ${{ secrets.SIEMENS_NPM_USER }}
      MAPTILER_KEY: ${{ secrets.MAPTILER_KEY }}

  publish-documentation:
    environment: github-pages
    runs-on: ubuntu-24.04
    permissions:
      pages: write
      id-token: write
    needs:
      - build-and-test
    steps:
      - uses: actions/configure-pages@v6
      - uses: actions/download-artifact@v8
        with:
          name: pages
          path: dist/design
      - uses: actions/download-artifact@v8
        with:
          name: coverage-reports
          path: coverage-reports
      - run: |
          cp coverage-reports/coverage-summary.json dist/design/coverage-summary.json
          cp -r coverage-reports dist/design/coverage
      - uses: actions/upload-pages-artifact@v4
        with:
          path: 'dist/design'
      - uses: actions/deploy-pages@v5
