- banner:
  - button "Toggle navigation"
  - heading "My application" [level=1]
  - button "Notifications" [expanded]
  - group "Notifications":
    - button "Message 1"
    - button "Message 2"
  - button "Toggle actions"
  - button "Lars Vegas"