- banner:
  - button "Toggle navigation"
  - heading "My application" [level=1]
  - button "Notifications"
  - button "Toggle actions"
  - button "Lars Vegas" [expanded]
  - group "Lars Vegas":
    - text: Lars Vegas lars.vegas@siemens.com Siemens AG Admin
    - button "Language" [expanded]
    - group "Language":
      - text: Selection has no effect!
      - button "German"
      - button "English"
    - button "Design"
    - button "Profile"