- banner:
  - button "Show navigation"
  - heading "My application" [level=1]
  - button "Notifications" [expanded]
  - group "Notifications":
    - button "Message 1"
    - button "Message 2"
  - button "Show actions"
  - button "Lars Vegas": LV