- banner:
  - button "Toggle navigation" [expanded]
  - text: My application
  - navigation "Main navigation":
    - link "Module 1":
      - /url: "#/viewer/viewer/m1"
    - button "Module 2" [expanded]
    - group "Module 2":
      - link "M2.1":
        - /url: "#/viewer/viewer/m2/1"
      - link "M2.2":
        - /url: "#/viewer/viewer/m2/2"
  - button "Notifications"
  - button "Toggle actions"
  - button "Lars Vegas"