- banner:
  - button "Show navigation" [expanded]
  - heading "My application" [level=1]
  - navigation "Main navigation":
    - link "Module 1":
      - /url: /m1
    - button "Module 2" [expanded]
    - group "Module 2":
      - link "M2.1":
        - /url: /m2/1
      - link "M2.2":
        - /url: /m2/2
  - button "Notifications"
  - button "Show actions"
  - button "Lars Vegas": LV