- banner:
  - button "Toggle navigation"
  - heading "My application" [level=1]
  - button "Notifications"
  - button "Toggle actions" [expanded]
  - button "Tenant 1"
  - button /\+\d+ Support/ [expanded]
  - group /\+\d+ Support/:
    - button "Help"
    - button "Contact"
  - button "Settings"
  - button "Lars Vegas"